// <auto-generated />
using System;
using Budget.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Budget.DB.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20250910031945_seed data")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Budget.DB.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = 0,
                            Balance = 0m,
                            Name = "Citizens"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = 1,
                            Balance = 0m,
                            Name = "Discover"
                        });
                });

            modelBuilder.Entity("Budget.DB.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Frequent",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Regular",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Budget.DB.Envelope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Envelopes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0m,
                            Budget = 0m,
                            CategoryId = 1,
                            Description = "",
                            Name = "Dining Out",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 0m,
                            Budget = 0m,
                            CategoryId = 1,
                            Description = "",
                            Name = "Groceries",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Balance = 0m,
                            Budget = 0m,
                            CategoryId = 2,
                            Description = "",
                            Name = "Gas",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("Budget.DB.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "New Year's Dinner",
                            TotalAmount = 100.00m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Groceries",
                            TotalAmount = 50.00m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gas",
                            TotalAmount = 30.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Budget.DB.TransactionDetail", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EnvelopeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TransactionId", "LineId");

                    b.HasIndex("EnvelopeId");

                    b.ToTable("TransactionDetail");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            LineId = 1,
                            Amount = 52m,
                            EnvelopeId = 1,
                            Notes = ""
                        },
                        new
                        {
                            TransactionId = 1,
                            LineId = 2,
                            Amount = 48m,
                            EnvelopeId = 2,
                            Notes = ""
                        },
                        new
                        {
                            TransactionId = 2,
                            LineId = 1,
                            Amount = 50m,
                            EnvelopeId = 3,
                            Notes = ""
                        },
                        new
                        {
                            TransactionId = 3,
                            LineId = 1,
                            Amount = 27m,
                            EnvelopeId = 3,
                            Notes = ""
                        },
                        new
                        {
                            TransactionId = 3,
                            LineId = 2,
                            Amount = 3m,
                            EnvelopeId = 2,
                            Notes = ""
                        });
                });

            modelBuilder.Entity("Budget.DB.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Patrick",
                            LastName = "Connelly"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Terri",
                            LastName = "Connelly"
                        });
                });

            modelBuilder.Entity("Budget.DB.Envelope", b =>
                {
                    b.HasOne("Budget.DB.Category", "Category")
                        .WithMany("Envelopes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Budget.DB.Transaction", b =>
                {
                    b.HasOne("Budget.DB.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Budget.DB.TransactionDetail", b =>
                {
                    b.HasOne("Budget.DB.Envelope", "Envelope")
                        .WithMany("Details")
                        .HasForeignKey("EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budget.DB.Transaction", "Transaction")
                        .WithMany("Details")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envelope");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Budget.DB.Category", b =>
                {
                    b.Navigation("Envelopes");
                });

            modelBuilder.Entity("Budget.DB.Envelope", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Budget.DB.Transaction", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Budget.DB.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
