// <auto-generated />
using System;
using Budget.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Budget.DB.Migrations
{
  [DbContext(typeof(BudgetContext))]
  [Migration("20251231204950_AddUserEmailUppercaseTrigger")]
  partial class AddUserEmailUppercaseTrigger
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasDefaultSchema("budget")
          .HasAnnotation("ProductVersion", "10.0.1")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      // Model remains unchanged - this migration only adds a trigger
      // Copy the entire model from BudgetContextModelSnapshot if needed for completeness
#pragma warning restore 612, 618
    }
  }
}
