<Project Sdk="Microsoft.NET.Sdk.Razor">
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RazorLangVersion>Latest</RazorLangVersion>
    <UserSecretsId>a0c2c5b7-5de1-4612-bd4e-43b30e547427</UserSecretsId>
    <!-- Suppress compiler warnings from generated Razor files -->
    <NoWarn>$(NoWarn);CS8669;CS0414</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Mapster" Version="9.0.0-pre01" />
    <PackageReference Include="MudBlazor" Version="9.0.0-preview.2" />
    <PackageReference Include="Syncfusion.Blazor" Version="32.2.4" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="32.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.3" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Budget.Shared\Budget.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

</Project>
