<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <UserSecretsId>963fdc62-1054-4faf-9967-f93e17074de8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="6.7.0" />
    <PackageReference Include="Mapster" Version="9.0.0-pre01" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Microsoft.Playwright" Version="1.58.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="MudBlazor" Version="9.0.0-preview.2" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Budget.ApiTests\Budget.ApiTests.csproj" />
    <ProjectReference Include="..\Budget.Client\Budget.Client.csproj" />
    <ProjectReference Include="..\Budget.Shared\Budget.Shared.csproj" />
    <ProjectReference Include="..\Budget.Web\Budget.Web.csproj" />
  </ItemGroup>

</Project>