name: Trigger auto deployment for budget

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/budget-AutoDeployTrigger-155f4a20-4462-4d0b-96d2-2c0717658565.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BUDGET_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BUDGET_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BUDGET_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrujhsryhos5xlq.azurecr.io
          registryUsername: ${{ secrets.BUDGET_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BUDGET_REGISTRY_PASSWORD }}
          containerAppName: budget
          resourceGroup: rg-BudgetApp2
          imageToBuild: acrujhsryhos5xlq.azurecr.io/budget:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


